export const ADD_PLACE_REQUEST = 'ADD_PLACE_REQUEST'
export const ADD_PLACE_SUCCESS = 'ADD_PLACE_SUCCESS'
export const ADD_PLACE_FAILURE = 'ADD_PLACE_FAILURE'

export const FETCH_PLACES_REQUEST = 'FETCH_PLACES_REQUEST'
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS'
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE'
